cursor      #B4B6A8

foreground  #ACAFAA
background  #050804

color0      #524C2F
color8      #5A5C58
color1      #484E44
color9      #484E44
color2      #787A78
color10     #787A78
color3      #6B8A05
color11     #6B8A05
color4      #F49641
color12     #F49641
color5      #BBBDA5
color13     #BBBDA5
color6      #FFEC00
color14     #FFEC00
color7      #80847E
color15     #80847E
