$background = rgb(050804)
$foreground = rgb(ACAFAA)
$accent = rgb(F49641)
$shadow = rgb(524C2F)
$subtle = rgb(5A5C58)
$active_border = rgb(F49641)
$active_border_2 = rgb(FFEC00)
$inactive_border = rgb(5A5C58)
$group_active_border = rgb(BBBDA5)
$group_inactive_border = rgb(5A5C58)
$accent_soft = rgb(FFEC00)
$accent_strong = rgb(FFEC00)
$warning = rgb(6B8A05)
$critical = rgb(484E44)
col.active_border = $active_border $active_border_2 45deg
col.inactive_border = $inactive_border
