$background = rgb({{background | strip}})
$foreground = rgb({{foreground | darken(0.7) | strip}})
$accent     = rgb({{color4 | darken(0.3) | saturate(0.5) | strip}})
$shadow     = rgb({{color7 | lighten(0.1) | strip}})
$subtle     = rgb({{color8 | darken(0.3) | saturate(0.2) | strip}})

$active_border         = rgb({{color4  | darken(0.3) | saturate(0.5) | strip}})
$active_border_2       = rgb({{color6  | darken(0.4) | saturate(0.5) | strip}})
$inactive_border       = rgb({{color7  | lighten(0.05) | strip}})
$group_active_border   = rgb({{color5  | darken(0.3) | saturate(0.5) | strip}})
$group_inactive_border = rgb({{color7  | lighten(0.05) | strip}})
$accent_soft           = rgb({{color6  | darken(0.4) | saturate(0.5) | strip}})
$accent_strong         = rgb({{color14 | darken(0.3) | saturate(0.5) | strip}})
$warning               = rgb({{color11 | darken(0.3) | saturate(0.5) | strip}})
$critical              = rgb({{color1  | darken(0.3) | saturate(0.5) | strip}})

col.active_border   = $active_border $active_border_2 45deg
col.inactive_border = $inactive_border
