cursor      {{cursor | darken(0.5)}}

foreground  {{foreground | darken(0.7)}}
background  #F8F8F8

color0      {{color0  | darken(0.5) | saturate(0.3)}}
color8      {{color8  | darken(0.4) | saturate(0.3)}}
color1      {{color1  | darken(0.3) | saturate(0.5)}}
color9      {{color9  | darken(0.3) | saturate(0.5)}}
color2      {{color2  | darken(0.3) | saturate(0.5)}}
color10     {{color10 | darken(0.3) | saturate(0.5)}}
color3      {{color3  | darken(0.4) | saturate(0.5)}}
color11     {{color11 | darken(0.3) | saturate(0.5)}}
color4      {{color4  | darken(0.3) | saturate(0.5)}}
color12     {{color12 | darken(0.3) | saturate(0.5)}}
color5      {{color5  | darken(0.3) | saturate(0.5)}}
color13     {{color13 | darken(0.3) | saturate(0.5)}}
color6      {{color6  | darken(0.4) | saturate(0.5)}}
color14     {{color14 | darken(0.3) | saturate(0.5)}}
color7      {{color7  | darken(0.2) | saturate(0.2)}}
color15     {{color15 | darken(0.5)}}
